#Minecraft server properties
#Wed Sep 23 22:42:02 BRT 2026
hellworld=false
level-name=world
max-players=20
online-mode=false
pvp=true
server-ip=
server-port=25565
spawn-animals=true
spawn-monsters=true
